name: easytag-jz
version: '2.4.3-0'
summary: Simple application for viewing and editing tags in audio files.
description: |
  EasyTAG is a simple application for viewing and editing tags in audio files.
  It supports MP3, MP2, MP4/AAC, FLAC, Ogg Opus, Ogg Speex, Ogg Vorbis,
  MusePack, Monkey's Audio, and WavPack files.

grade: stable
confinement: strict

slots:
  dbus-easytag:
    interface: dbus
    name: org.gnome.EasyTAG
    bus: session

plugs:
    gnome-3-26-1604:
      interface: content
      target: $SNAP/gnome-platform
      default-provider: gnome-3-26-1604:gnome-3-26-1604

apps:
  easytag-jz:
    command: desktop-launch easytag
    plugs: [unity7, home, gsettings, gnome-3-26-1604, removable-media]
    slots: [dbus-easytag]

parts:
  easytag:
    plugin: autotools
    source: https://download.gnome.org/sources/easytag/2.4/easytag-2.4.3.tar.xz
    build-packages:
      - docbook-xml
      - docbook-xsl
      - gettext
      - intltool
      - libflac-dev
      - libglib2.0-dev
      - libgtk-3-dev
      - libid3-3.8.3-dev
      - libid3tag0-dev
      - libogg-dev
      - libopusfile-dev
      - libspeex-dev
      - libtag1-dev
      - libvorbis-dev
      - libwavpack-dev
      - yelp-tools
      - zlib1g-dev
      - gnome-icon-theme
    prepare: |
      cp -v ../../../insert-text.png data/images/
      for p in ../../../*.diff
      do
        cat $p | patch -p1
      done
    organize:
      share/glib-2.0/schemas/*: usr/share/glib-2.0/schemas/
      share/icons: usr/share/
      share/help: usr/share/
      share/locale: usr/share/
      share/appdata: usr/share
    prime:
      - -share
    after: [desktop-gnome-platform]

  # workaround snapcraft trying to outsmart us by copying ldd listed libraries
  workaround:
    plugin: nil
    prime:
      - "-*"
